id: ICE8BDEEB
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:24:12.434477'
last_modified: '2022-06-18T22:24:12.434491'
parser: null
source_metadata:
  title: Shākya don grubs Sakya Genealogy
  author: shAkyai dge slong shAkya don grub dpal bzang po/
  description: 'Digital version 1.0 {Wylie}; WYLIE COPY of master xml (completed:
    2018-09-06); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Lobsang Gyaltsen, Dharamsala (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:tshe ring grong shar/ (ut)
  text_witnesses: https://sakyaresearch.org/sources/2436
  bases:
    25bf:
      title: Shākya don grubs Sakya Genealogy
      order: 1
      base_file: 25bf.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
